#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Output\ConsoleOutput;

/*
|--------------------------------------------------------------------------
| Create The Application
|--------------------------------------------------------------------------
|
| First we need to get an application instance. This creates an instance
| of the application / container and bootstraps the application so it
| is ready to receive HTTP / Console requests from the environment.
|
*/

// echo shell_exec('composer dumpautoload 2>&1');
$app = require __DIR__.'/bootstrap/app.php';
$app->register(Vluzrmos\Tinker\TinkerServiceProvider::class);

/*
|--------------------------------------------------------------------------
| Run The Artisan Application
|--------------------------------------------------------------------------
|
| When we run the console application, the current CLI command will be
| executed in this console and the response sent back to a terminal
| or another output device for the developers. Here goes nothing!
|
*/

$kernel = $app->make(
    'Illuminate\Contracts\Console\Kernel'
);

$outputFormatter = new \Symfony\Component\Console\Formatter\OutputFormatter(false, [
    'error' => new \Symfony\Component\Console\Formatter\OutputFormatterStyle('yellow', 'blue')
]);

$output = new ConsoleOutput(ConsoleOutput::VERBOSITY_NORMAL, null, $outputFormatter);

$status = $kernel->handle(
    $input = new Symfony\Component\Console\Input\ArgvInput,
    $output
);

exit($status);